[versions]
application = "0.0.1"
kotlin = "1.6.21"
sqldelight = "1.5.3"
ksp = "1.6.21-1.0.5"
ktor = "2.0.1"
logback = "1.2.1"
coroutines = "1.6.0"
kotlinInject = "0.4.1"
turbine = "0.7.0"
sqliteDriver = "3.36.0.3"
jsoup = "1.13.1"
dateTime = "0.6.3"
jUnit5 = "5.7.0"

[plugins]
application-package = { id = "com.kamilh.volleyballstats" }

[libraries]
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
plugin-sqldelight = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqldelight" }
plugin-ksp = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-hostCommon = { module = "io.ktor:ktor-server-host-common", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-statusPages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktor-server-contentNegotiate = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-test = { module = "io.ktor:ktor-server-tests", version.ref = "ktor" }

ktor-client-contentNegotiate = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-jvm = { module = "io.ktor:ktor-client-apache", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-test = { module = "io.ktor:ktor-client-tests", version.ref = "ktor" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

inject-runtime = { module = "me.tatarka.inject:kotlin-inject-runtime", version.ref = "kotlinInject" }
inject-compiler = { module = "me.tatarka.inject:kotlin-inject-compiler-ksp", version.ref = "kotlinInject" }

sqldelight-driver = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-coroutines-jvm = { module = "com.squareup.sqldelight:coroutines-extensions-jvm", version.ref = "sqldelight" }

turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqliteDriver" }

jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }

datetime = { module = "io.islandtime:core", version.ref = "dateTime" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jUnit5" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jUnit5" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jUnit5" }