package com.kamilh.volleyballstats.ui.theme

import androidx.compose.ui.graphics.Color

@Suppress("MagicNumber")
object AppColor {
    val GreyDark = Color(color = 0xFF1A1D23)
    val Grey = Color(color = 0xFF2A3038)

    val White = Color.White

    val LightPrimary = Color(0xFF96490B)
    val LightOnPrimary = Color(0xFFFFFFFF)
    val LightPrimaryContainer = Color(0xFFFFDBC8)
    val LightOnPrimaryContainer = Color(0xFF321300)
    val LightSecondary = Color(0xFF755847)
    val LightOnSecondary = Color(0xFFFFFFFF)
    val LightSecondaryContainer = Color(0xFFFFDBC8)
    val LightOnSecondaryContainer = Color(0xFF2B1709)
    val LightTertiary = Color(0xFF006878)
    val LightOnTertiary = Color(0xFFFFFFFF)
    val LightTertiaryContainer = Color(0xFFA6EEFF)
    val LightOnTertiaryContainer = Color(0xFF001F25)
    val LightError = Color(0xFFBA1A1A)
    val LightErrorContainer = Color(0xFFFFDAD6)
    val LightOnError = Color(0xFFFFFFFF)
    val LightOnErrorContainer = Color(0xFF410002)
    val LightBackground = Color(0xFFFFFBFF)
    val LightOnBackground = Color(0xFF311300)
    val LightSurface = Color(0xFFFFFBFF)
    val LightOnSurface = Color(0xFF311300)
    val LightSurfaceVariant = Color(0xFFF4DED3)
    val LightOnSurfaceVariant = Color(0xFF52443C)
    val LightOutline = Color(0xFF85746B)
    val LightInverseOnSurface = Color(0xFFFFEDE4)
    val LightInverseSurface = Color(0xFF512400)
    val LightInversePrimary = Color(0xFFFFB68A)
    val LightSurfaceTint = Color(0xFF96490B)

    val DarkPrimary = Color(0xFFFFB68A)
    val DarkOnPrimary = Color(0xFF522300)
    val DarkPrimaryContainer = Color(0xFF743500)
    val DarkOnPrimaryContainer = Color(0xFFFFDBC8)
    val DarkSecondary = Color(0xFFE5BFA9)
    val DarkOnSecondary = Color(0xFF432B1C)
    val DarkSecondaryContainer = Color(0xFF5C4131)
    val DarkOnSecondaryContainer = Color(0xFFFFDBC8)
    val DarkTertiary = Color(0xFF53D7F1)
    val DarkOnTertiary = Color(0xFF00363F)
    val DarkTertiaryContainer = Color(0xFF004E5B)
    val DarkOnTertiaryContainer = Color(0xFFA6EEFF)
    val DarkError = Color(0xFFFFB4AB)
    val DarkErrorContainer = Color(0xFF93000A)
    val DarkOnError = Color(0xFF690005)
    val DarkOnErrorContainer = Color(0xFFFFDAD6)
    val DarkSurfaceVariant = Color(0xFF52443C)
    val DarkOnSurfaceVariant = Color(0xFFD7C2B8)
    val DarkOutline = Color(0xFF9F8D84)
    val DarkInverseOnSurface = Color(0xFF311300)
    val DarkInverseSurface = Color(0xFFFFDBC7)
    val DarkInversePrimary = Color(0xFF96490B)
    val DarkSurfaceTint = Color(0xFFFFB68A)

    val TurquoiseLightPrimary = Color(0xFF006878)
    val TurquoiseLightOnPrimary = Color(0xFFFFFFFF)
    val TurquoiseLightPrimaryContainer = Color(0xFFA6EEFF)
    val TurquoiseLightOnPrimaryContainer = Color(0xFF001F25)
    val TurquoiseLightSecondary = Color(0xFF4B6268)
    val TurquoiseLightOnSecondary = Color(0xFFFFFFFF)
    val TurquoiseLightSecondaryContainer = Color(0xFFCDE7EE)
    val TurquoiseLightOnSecondaryContainer = Color(0xFF051F24)

    val TurquoiseDarkPrimary = Color(0xFF53D7F1)
    val TurquoiseDarkOnPrimary = Color(0xFF00363F)
    val TurquoiseDarkPrimaryContainer = Color(0xFF004E5B)
    val TurquoiseDarkOnPrimaryContainer = Color(0xFFA6EEFF)
    val TurquoiseDarkSecondary = Color(0xFFB2CBD1)
    val TurquoiseDarkOnSecondary = Color(0xFF1C3439)
    val TurquoiseDarkSecondaryContainer = Color(0xFF334A50)
    val TurquoiseDarkOnSecondaryContainer = Color(0xFFCDE7EE)
}
