@file:Suppress("TopLevelPropertyNaming")

package com.kamilh.volleyballstats.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

internal val OrangeLightColors = lightColorScheme(
    primary = AppColor.LightPrimary,
    onPrimary = AppColor.LightOnPrimary,
    primaryContainer = AppColor.LightPrimaryContainer,
    onPrimaryContainer = AppColor.LightOnPrimaryContainer,
    secondary = AppColor.LightSecondary,
    onSecondary = AppColor.LightOnSecondary,
    secondaryContainer = AppColor.LightSecondaryContainer,
    onSecondaryContainer = AppColor.LightOnSecondaryContainer,
    tertiary = AppColor.LightTertiary,
    onTertiary = AppColor.LightOnTertiary,
    tertiaryContainer = AppColor.LightTertiaryContainer,
    onTertiaryContainer = AppColor.LightOnTertiaryContainer,
    error = AppColor.LightError,
    errorContainer = AppColor.LightErrorContainer,
    onError = AppColor.LightOnError,
    onErrorContainer = AppColor.LightOnErrorContainer,
    background = AppColor.LightBackground,
    onBackground = AppColor.LightOnBackground,
    surface = AppColor.LightSurface,
    onSurface = AppColor.LightOnSurface,
    surfaceVariant = AppColor.LightSurfaceVariant,
    onSurfaceVariant = AppColor.LightOnSurfaceVariant,
    outline = AppColor.LightOutline,
    inverseOnSurface = AppColor.LightInverseOnSurface,
    inverseSurface = AppColor.LightInverseSurface,
    inversePrimary = AppColor.LightInversePrimary,
    surfaceTint = AppColor.LightSurfaceTint,
)

internal val OrangeDarkColors = darkColorScheme(
    primary = AppColor.DarkPrimary,
    onPrimary = AppColor.DarkOnPrimary,
    primaryContainer = AppColor.DarkPrimaryContainer,
    onPrimaryContainer = AppColor.DarkOnPrimaryContainer,
    secondary = AppColor.DarkSecondary,
    onSecondary = AppColor.DarkOnSecondary,
    secondaryContainer = AppColor.DarkSecondaryContainer,
    onSecondaryContainer = AppColor.DarkOnSecondaryContainer,
    tertiary = AppColor.DarkTertiary,
    onTertiary = AppColor.DarkOnTertiary,
    tertiaryContainer = AppColor.DarkTertiaryContainer,
    onTertiaryContainer = AppColor.DarkOnTertiaryContainer,
    error = AppColor.DarkError,
    errorContainer = AppColor.DarkErrorContainer,
    onError = AppColor.DarkOnError,
    onErrorContainer = AppColor.DarkOnErrorContainer,
    background = AppColor.GreyDark,
    onBackground = AppColor.White,
    surface = AppColor.Grey,
    onSurface = AppColor.White,
    surfaceVariant = AppColor.DarkSurfaceVariant,
    onSurfaceVariant = AppColor.DarkOnSurfaceVariant,
    outline = AppColor.DarkOutline,
    inverseOnSurface = AppColor.DarkInverseOnSurface,
    inverseSurface = AppColor.DarkInverseSurface,
    inversePrimary = AppColor.DarkInversePrimary,
    surfaceTint = AppColor.DarkSurfaceTint,
)

internal val TurquoiseLightColors = lightColorScheme(
    primary = AppColor.TurquoiseLightPrimary,
    onPrimary = AppColor.TurquoiseLightOnPrimary,
    primaryContainer = AppColor.TurquoiseLightPrimaryContainer,
    onPrimaryContainer = AppColor.TurquoiseLightOnPrimaryContainer,
    secondary = AppColor.TurquoiseLightSecondary,
    onSecondary = AppColor.TurquoiseLightOnSecondary,
    secondaryContainer = AppColor.TurquoiseLightSecondaryContainer,
    onSecondaryContainer = AppColor.TurquoiseLightOnSecondaryContainer,
    tertiary = AppColor.LightPrimary,
    onTertiary = AppColor.LightOnPrimary,
    tertiaryContainer = AppColor.LightPrimaryContainer,
    onTertiaryContainer = AppColor.LightOnPrimaryContainer,
    error = AppColor.LightError,
    errorContainer = AppColor.LightErrorContainer,
    onError = AppColor.LightOnError,
    onErrorContainer = AppColor.LightOnErrorContainer,
    background = AppColor.LightBackground,
    onBackground = AppColor.LightOnBackground,
    surface = AppColor.LightSurface,
    onSurface = AppColor.LightOnSurface,
    surfaceVariant = AppColor.LightSurfaceVariant,
    onSurfaceVariant = AppColor.LightOnSurfaceVariant,
    outline = AppColor.LightOutline,
    inverseOnSurface = AppColor.LightInverseOnSurface,
    inverseSurface = AppColor.LightInverseSurface,
    inversePrimary = AppColor.LightInversePrimary,
    surfaceTint = AppColor.LightSurfaceTint,
)

internal val TurquoiseDarkColors = darkColorScheme(
    primary = AppColor.TurquoiseDarkPrimary,
    onPrimary = AppColor.TurquoiseDarkOnPrimary,
    primaryContainer = AppColor.TurquoiseDarkPrimaryContainer,
    onPrimaryContainer = AppColor.TurquoiseDarkOnPrimaryContainer,
    secondary = AppColor.TurquoiseDarkSecondary,
    onSecondary = AppColor.TurquoiseDarkOnSecondary,
    secondaryContainer = AppColor.TurquoiseDarkSecondaryContainer,
    onSecondaryContainer = AppColor.TurquoiseDarkOnSecondaryContainer,
    tertiary = AppColor.DarkPrimary,
    onTertiary = AppColor.DarkOnPrimary,
    tertiaryContainer = AppColor.DarkPrimaryContainer,
    onTertiaryContainer = AppColor.DarkOnPrimaryContainer,
    error = AppColor.DarkError,
    errorContainer = AppColor.DarkErrorContainer,
    onError = AppColor.DarkOnError,
    onErrorContainer = AppColor.DarkOnErrorContainer,
    background = AppColor.GreyDark,
    onBackground = AppColor.White,
    surface = AppColor.Grey,
    onSurface = AppColor.White,
    surfaceVariant = AppColor.DarkSurfaceVariant,
    onSurfaceVariant = AppColor.DarkOnSurfaceVariant,
    outline = AppColor.DarkOutline,
    inverseOnSurface = AppColor.DarkInverseOnSurface,
    inverseSurface = AppColor.DarkInverseSurface,
    inversePrimary = AppColor.DarkInversePrimary,
    surfaceTint = AppColor.DarkSurfaceTint,
)
