package com.kamilh.volleyballstats.clients.app.ui.theme

import androidx.compose.ui.graphics.Color

val Orange = Color(color = 0xFFd98875)
val OrangeDark = Color(color = 0xFFa84f22)
val OrangeLight = Color(color = 0x80ffad7a)
val Turquoise = Color(color = 0xFF24a8bf)
val TurquoiseDark = Color(color = 0xFF00798f)
val TurquoiseLight = Color(color = 0xFF67daf2)

val GreyLight = Color(color = 0xFF666F78)
val GreyDark = Color(color = 0xFF1A1D23)
val Grey = Color(color = 0xFF2A3038)

val White = Color.White

val LightPrimary = Color(0xFF96490B)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFDBC8)
val LightOnPrimaryContainer = Color(0xFF321300)
val LightSecondary = Color(0xFF755847)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFDBC8)
val LightOnSecondaryContainer = Color(0xFF2B1709)
val LightTertiary = Color(0xFF006878)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFA6EEFF)
val LightOnTertiaryContainer = Color(0xFF001F25)
val LightError = Color(0xFFBA1A1A)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnError = Color(0xFFFFFFFF)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFFBFF)
val LightOnBackground = Color(0xFF311300)
val LightSurface = Color(0xFFFFFBFF)
val LightOnSurface = Color(0xFF311300)
val LightSurfaceVariant = Color(0xFFF4DED3)
val LightOnSurfaceVariant = Color(0xFF52443C)
val LightOutline = Color(0xFF85746B)
val LightInverseOnSurface = Color(0xFFFFEDE4)
val LightInverseSurface = Color(0xFF512400)
val LightInversePrimary = Color(0xFFFFB68A)
val LightSurfaceTint = Color(0xFF96490B)

val DarkPrimary = Color(0xFFFFB68A)
val DarkOnPrimary = Color(0xFF522300)
val DarkPrimaryContainer = Color(0xFF743500)
val DarkOnPrimaryContainer = Color(0xFFFFDBC8)
val DarkSecondary = Color(0xFFE5BFA9)
val DarkOnSecondary = Color(0xFF432B1C)
val DarkSecondaryContainer = Color(0xFF5C4131)
val DarkOnSecondaryContainer = Color(0xFFFFDBC8)
val DarkTertiary = Color(0xFF53D7F1)
val DarkOnTertiary = Color(0xFF00363F)
val DarkTertiaryContainer = Color(0xFF004E5B)
val DarkOnTertiaryContainer = Color(0xFFA6EEFF)
val DarkError = Color(0xFFFFB4AB)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnError = Color(0xFF690005)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkSurfaceVariant = Color(0xFF52443C)
val DarkOnSurfaceVariant = Color(0xFFD7C2B8)
val DarkOutline = Color(0xFF9F8D84)
val DarkInverseOnSurface = Color(0xFF311300)
val DarkInverseSurface = Color(0xFFFFDBC7)
val DarkInversePrimary = Color(0xFF96490B)
val DarkSurfaceTint = Color(0xFFFFB68A)
