name: build-server

on:
  push:
    branches: [ "master", "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Run building job
        run: /home/actions-runner/build.sh ${GITHUB_REF##*/}
